---
debug: true
username: jsmith@gmaildotcom
password: ABCDE12345
to: jdoe@yourdomaindotcom
subject: Scanned document
body: |
  Hello,
  Attached is a scanned copy of the document under discussion.
  Please review, Thanks.
content_type: html
file: []   
